import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../../components/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CallForPapersPage() {
  return (
    <main className="pt-24">
      {/* --- Hero Section --- */}
      <section className="bg-blue-50 py-20 text-center">
        <h1 className="text-4xl md:text-5xl font-bold text-gray-900">
          Call For Papers
        </h1>

        <p className="mt-4 max-w-2xl mx-auto text-lg text-gray-600">
          Explore our technical tracks and submission guidelines.
        </p>
      </section>

      {/* --- Keynote Announcement Card --- */}
      <section className="pb-28">
        <div className="max-w-6xl mx-auto px-4">
          <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-blue-900 to-blue-800 px-8 py-20 text-center text-white shadow-xl">
            {/* Decorative circles */}
            <div className="absolute -top-20 -left-20 h-64 w-64 rounded-full bg-white/10"></div>
            <div className="absolute -bottom-24 -right-24 h-72 w-72 rounded-full bg-white/10"></div>

            {/* Description */}

            <div className="mt-8 max-w-4xl mx-auto space-y-6 text-base md:text-lg leading-relaxed text-justify text-white/95">
              <p>
                You are invited to submit abstracts for{" "}
                <strong>IRCUWU2025</strong> prepared using the given template.
                The official language of the conference is English. Abstracts
                written in English will be accepted for both poster and oral
                presentation formats of the conference. The work presented
                should be related to any of the fourteen thematic areas listed
                in the section <strong>“Conference Tracks”</strong> of this
                website or to any areas falling under the conference theme.
              </p>

              <p>
                In addition to the Abstract, an{" "}
                <strong>Extended Abstract</strong> (i.e., a more elaborated
                version of the Abstract) <strong>must be submitted</strong> to
                support the reviewers in comprehending the research more
                thoroughly during the review process. It will be used as a
                preliminary filter by the Review Committee in case subsequent
                full-paper manuscript submissions to the journals published by
                Uva Wellassa University (
                <em>
                  Journal of Management and Tourism Research or Journal of
                  Agriculture and Value Addition or Journal of Technology and
                  Value Addition or Journal of Science and Technology or Sri
                  Lankan Journal of Applied Sciences
                </em>
                ) are to be considered.
              </p>

              <p>
                For your submission to be considered for review, the{" "}
                <strong>Extended Abstract</strong> must be uploaded to the{" "}
                <a
                  href="https://cmt3.research.microsoft.com/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-semibold underline underline-offset-4 text-white hover:text-blue-200"
                >
                  CMT portal for IRCUWU2025
                </a>
                .{" "}
                <strong>
                  Submissions without this document will be automatically
                  disqualified.
                </strong>
              </p>

              <p>
                If your Abstract is accepted, you will be asked to submit the
                camera-ready version of the Abstract before the stipulated
                deadline.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* --- Conference Tracks Section --- */}
      <section className="bg-white py-28">
        <div className="max-w-7xl mx-auto px-4">
          {/* Title */}
          <h2 className="text-center text-4xl md:text-5xl font-bold text-gray-900 mb-6">
            Conference Tracks
          </h2>

          <p className="text-center max-w-3xl mx-auto text-lg text-gray-600 mb-16">
            Explore the diverse thematic areas covered by the conference.
          </p>

          {/* Tracks Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {[
              "Aquatic Sciences",
              "Business Economics, Accountancy & Finance",
              "Computing & Informatics",
              "Engineering and Technology",
              "Entrepreneurship & Business Management",
              "Environmental Sciences",
              "Food Science & Bioprocesses",
              "Hospitality and Tourism",
              "Library & Information Sciences",
              "Human Resource Development",
              "Material and Mineral Sciences",
              "Medical Sciences",
              "Sustainable Animal Production",
              "Sustainable Crop Production",
            ].map((track, index) => (
              <div
                key={index}
                className="group rounded-2xl border bg-gray-50 p-6 transition-all duration-300 hover:bg-white hover:shadow-lg hover:border-blue-500"
              >
                {/* Track Number */}
                <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-full bg-blue-100 text-sm font-bold text-blue-800">
                  {index + 1}
                </div>

                {/* Track Title */}
                <h3 className="text-lg font-semibold text-gray-900 group-hover:text-blue-800 transition-colors">
                  {track}
                </h3>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* --- Downloads Section --- */}
      <section className="bg-gradient-to-b from-blue-50 to-white py-28">
        <div className="max-w-7xl mx-auto px-4">
          {/* Title */}
          <h2 className="text-center text-4xl md:text-5xl font-bold text-gray-900 mb-6">
            Downloads
          </h2>

          <p className="text-center max-w-3xl mx-auto text-lg text-gray-600 mb-16">
            Access all required templates, guidelines, and supporting documents
            for your submission and participation.
          </p>

          {/* Download List */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              "Instructions to Authors",
              "Abstract Template",
              "Extended Abstract Template",
              "Camera-ready Template",
              "Author Declaration Form",
              "Virtual Background IRCUWU2025",
              "Oral Presentation Template",
              "Video Submission Guideline for Oral Presentations",
              "Poster Presentation Template",
              "Video Submission Guideline for Poster Presentations",
              "Referencing Guidelines",
            ].map((item, index) => (
              <div
                key={index}
                className="flex items-center justify-between rounded-xl bg-white p-5 border shadow-sm transition-all duration-300 hover:border-blue-500 hover:shadow-md"
              >
                {/* File name */}
                <span className="text-gray-800 font-medium">{item}</span>

                {/* Download button */}
                <button
                  type="button"
                  className="rounded-md bg-blue-900 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-800 transition"
                >
                  Download
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
